# Generated by Django 4.2 on 2023-04-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_friendrequest_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='message',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="inviter's message"),
        ),
    ]
