# Generated by Django 4.1.7 on 2023-03-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='avatar',
            field=models.ImageField(blank=True, default='images/DEFAULT_CHAT_AVATAR.jpg', upload_to='images/chat_avatars/'),
        ),
    ]
