# Generated by Django 4.2.1 on 2023-05-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="text content")),
                (
                    "date_create",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date of creation"
                    ),
                ),
                (
                    "is_edited",
                    models.BooleanField(default=False, verbose_name="is edited"),
                ),
            ],
            options={
                "verbose_name": "comment",
                "verbose_name_plural": "comments",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="text content")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/post_attachments/",
                        verbose_name="photo attachment",
                    ),
                ),
                (
                    "date_create",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date of creation"
                    ),
                ),
                (
                    "is_edited",
                    models.BooleanField(default=False, verbose_name="is edited"),
                ),
            ],
            options={
                "verbose_name": "post",
                "verbose_name_plural": "posts",
            },
        ),
    ]
